language: go
arch:
    - amd64
    - ppc64le

sudo: false

go:
  - 1.4
  - 1.5
  - 1.6
  - tip
  
# Disable version in power system
jobs: 
  exclude:
    - arch: ppc64le
      go: "1.4"  
        
script:
  - go test -bench . -benchmem -v ./...
